## macandtech routes

routes:
  /: home
  /blog/archive/:
    controller: channel
    template: archive

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /blog/tag/{slug}/
  author: /blog/author/{slug}/